Repository googleapis/java-aiplatform, pull requests merged in 2020-09, with the labels that each got.

#8 chore: generate README
  README.md
  grpc-google-cloud-aiplatform-v1beta1/pom.xml
  synth.metadata
Labels: automerge, cla: yes, context: none

#13 chore: regenerate common templates
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#21 chore(java): use separate autosynth job for README
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#22 samples: added new added env ars for ucaip samples
  .kokoro/build.sh
  .kokoro/nightly/samples.cfg
  .kokoro/presubmit/samples.cfg
Labels: cla: yes

#24 samples: update pom.xml (s) in the samples dir
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
Labels: cla: yes
