Repository googleapis/java-aiplatform, pull requests merged in 2020-12, with the labels that each got.

#66 chore: regenerate common templates
  .github/workflows/formatting.yaml
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: partial

#114 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#115 chore: regenerate common templates
  .github/blunderbuss.yml
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  .kokoro/common.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#117 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#119 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#108 feat: adds ValueConverter utility and demo samples
  google-cloud-aiplatform/pom.xml
  google-cloud-aiplatform/src/main/java/com/google/cloud/aiplatform/util/ValueConverter.java
  google-cloud-aiplatform/src/test/java/com/google/cloud/aiplatform/util/ValueConverterTest.java
  samples/snippets/pom.xml
  samples/snippets/src/main/java/aiplatform/CreateTrainingPipelineImageClassificationSample.java
  samples/snippets/src/main/java/aiplatform/PredictImageClassificationSample.java
  samples/snippets/src/main/java/aiplatform/PredictTextClassificationSingleLabelSample.java
Labels: cla: yes, samples

#124 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#126 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: cla: yes, context: full, merge
