Repository googleapis/java-aiplatform, pull requests merged in 2020-11, with the labels that each got.

#44 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#18 samples: ucaip samples batch 3 of 6
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/BatchPredictionJob.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/DeployedModel.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/DeployedModelOrBuilder.java
  proto-google-cloud-aiplatform-v1beta1/src/main/proto/google/cloud/aiplatform/v1beta1/endpoint.proto
  samples/snippets/pom.xml
  samples/snippets/src/main/java/aiplatform/CancelTrainingPipelineSample.java
  samples/snippets/src/main/java/aiplatform/CreateDatasetTabularBigquerySample.java
  samples/snippets/src/main/java/aiplatform/CreateDatasetTabularGcsSample.java
  samples/snippets/src/main/java/aiplatform/CreateTrainingPipelineTabularClassificationSample.java
  samples/snippets/src/main/java/aiplatform/CreateTrainingPipelineTabularRegressionSample.java
  samples/snippets/src/main/java/aiplatform/DeleteDatasetSample.java
  samples/snippets/src/main/java/aiplatform/DeleteExportModelSample.java
  samples/snippets/src/main/java/aiplatform/DeleteTrainingPipelineSample.java
  samples/snippets/src/main/java/aiplatform/ExportModelTabularClassificationSample.java
  samples/snippets/src/main/java/aiplatform/GetModelEvaluationTabularClassificationSample.java
  samples/snippets/src/main/java/aiplatform/GetModelEvaluationTabularRegressionSample.java
  samples/snippets/src/main/java/aiplatform/PredictTabularClassificationSample.java
  samples/snippets/src/main/java/aiplatform/PredictTabularRegressionSample.java
  samples/snippets/src/test/java/aiplatform/CreateDatasetTabularBigquerySampleTest.java
  samples/snippets/src/test/java/aiplatform/CreateDatasetTabularGcsSampleTest.java
  samples/snippets/src/test/java/aiplatform/CreateTrainingPipelineTabularClassificationSampleTest.java
  samples/snippets/src/test/java/aiplatform/CreateTrainingPipelineTabularRegressionSampleTest.java
  samples/snippets/src/test/java/aiplatform/ExportModelTabularClassificationSampleTest.java
  samples/snippets/src/test/java/aiplatform/GetModelEvaluationTabularClassificationSampleTest.java
  samples/snippets/src/test/java/aiplatform/GetModelEvaluationTabularRegressionSampleTest.java
  samples/snippets/src/test/java/aiplatform/PredictTabularClassificationSampleTest.java
  samples/snippets/src/test/java/aiplatform/PredictTabularRegressionSampleTest.java
Labels: cla: yes, samples

#17 samples: ucaip samples batch 6 of 6
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/aiplatform/CreateDatasetTextSample.java
  samples/snippets/src/main/java/aiplatform/CreateTrainingPipelineTextClassificationSample.java
  samples/snippets/src/main/java/aiplatform/CreateTrainingPipelineTextEntityExtractionSample.java
  samples/snippets/src/main/java/aiplatform/CreateTrainingPipelineTextSentimentAnalysisSample.java
  samples/snippets/src/main/java/aiplatform/GetModelEvaluationTextClassificationSample.java
  samples/snippets/src/main/java/aiplatform/GetModelEvaluationTextEntityExtractionSample.java
  samples/snippets/src/main/java/aiplatform/GetModelEvaluationTextSentimentAnalysisSample.java
  samples/snippets/src/main/java/aiplatform/ImportDataTextClassificationSingleLabelSample.java
  samples/snippets/src/main/java/aiplatform/ImportDataTextEntityExtractionSample.java
  samples/snippets/src/main/java/aiplatform/ImportDataTextSentimentAnalysisSample.java
  samples/snippets/src/main/java/aiplatform/PredictTextClassificationSingleLabelSample.java
  samples/snippets/src/main/java/aiplatform/PredictTextEntityExtractionSample.java
  samples/snippets/src/main/java/aiplatform/PredictTextSentimentAnalysisSample.java
  samples/snippets/src/test/java/aiplatform/CreateDatasetTextSampleTest.java
  samples/snippets/src/test/java/aiplatform/CreateTrainingPipelineTextClassificationSampleTest.java
  samples/snippets/src/test/java/aiplatform/CreateTrainingPipelineTextEntityExtractionSampleTest.java
  samples/snippets/src/test/java/aiplatform/CreateTrainingPipelineTextSentimentAnalysisSampleTest.java
  samples/snippets/src/test/java/aiplatform/GetModelEvaluationTextClassificationSampleTest.java
  samples/snippets/src/test/java/aiplatform/GetModelEvaluationTextEntityExtractionSampleTest.java
  samples/snippets/src/test/java/aiplatform/GetModelEvaluationTextSentimentAnalysisSampleTest.java
  samples/snippets/src/test/java/aiplatform/ImportDataSampleTest.java
  samples/snippets/src/test/java/aiplatform/PredictTextClassificationSingleLabelSampleTest.java
  samples/snippets/src/test/java/aiplatform/PredictTextEntityExtractionSampleTest.java
  samples/snippets/src/test/java/aiplatform/PredictTextSentimentAnalysisSampleTest.java
Labels: automerge, cla: yes, samples

#45 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#48 chore: delete ununsed format script
  samples/snippets/format.sh
Labels: cla: yes

#49 docs: fix generated typos
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/BatchPredictionJob.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/DeployedModel.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/DeployedModelOrBuilder.java
  proto-google-cloud-aiplatform-v1beta1/src/main/proto/google/cloud/aiplatform/v1beta1/endpoint.proto
  synth.metadata
Labels: automerge, cla: yes, context: none

#46 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#51 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#61 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#58 chore: add `@googleapis/ml-apis` as codeowner team
  .github/CODEOWNERS
  .repo-metadata.json
Labels: automerge, cla: yes

#62 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#63 chore: ignore generating templates that are hand modified
  synth.py
Labels: cla: yes
