Repository googleapis/java-aiplatform, pull requests merged in 2021-03, with the labels that each got.

#195 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#185 chore: replaced hard-coded values with env vars
  samples/snippets/src/test/java/aiplatform/CreateDatasetSampleTest.java
  samples/snippets/src/test/java/aiplatform/CreateEndpointSampleTest.java
  samples/snippets/src/test/java/aiplatform/CreateTrainingPipelineSampleTest.java
  samples/snippets/src/test/java/aiplatform/DeployModelCustomTrainedModelSampleTest.java
  samples/snippets/src/test/java/aiplatform/DeployModelSampleTest.java
  samples/snippets/src/test/java/aiplatform/ExportModelSampleTest.java
  samples/snippets/src/test/java/aiplatform/GetModelEvaluationSampleTest.java
  samples/snippets/src/test/java/aiplatform/GetModelEvaluationSliceSampleTest.java
  samples/snippets/src/test/java/aiplatform/GetModelSampleTest.java
  samples/snippets/src/test/java/aiplatform/ListModelEvaluationSliceSampleTest.java
Labels: api: aiplatform, cla: yes

#196 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#199 chore: Re-generated to pick up changes from synthtool
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  google-cloud-aiplatform/src/main/java/com/google/cloud/aiplatform/v1/gapic_metadata.json
  google-cloud-aiplatform/src/main/java/com/google/cloud/aiplatform/v1beta1/gapic_metadata.json
  synth.metadata
Labels: cla: yes, context: partial

#200 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#201 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#205 build(java): update autorelease title check in response to the new multi release branch changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#208 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#211 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#213 chore: remove staging bucket v2
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
