Repository googleapis/java-aiplatform, pull requests merged in 2021-01, with the labels that each got.

#75 chroe(docs): update description in metadata
  .repo-metadata.json
Labels: cla: yes

#130 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#136 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#137 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#140 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#134 samples: adds enhanced library samples
  samples/snippets/pom.xml
  samples/snippets/src/main/java/aiplatform/CreateTrainingPipelineImageObjectDetectionSample.java
  samples/snippets/src/main/java/aiplatform/CreateTrainingPipelineTabularClassificationSample.java
  samples/snippets/src/main/java/aiplatform/CreateTrainingPipelineTabularRegressionSample.java
  samples/snippets/src/main/java/aiplatform/CreateTrainingPipelineTextClassificationSample.java
  samples/snippets/src/main/java/aiplatform/CreateTrainingPipelineTextEntityExtractionSample.java
  samples/snippets/src/main/java/aiplatform/CreateTrainingPipelineTextSentimentAnalysisSample.java
  samples/snippets/src/main/java/aiplatform/CreateTrainingPipelineVideoActionRecognitionSample.java
  samples/snippets/src/main/java/aiplatform/CreateTrainingPipelineVideoClassificationSample.java
  samples/snippets/src/main/java/aiplatform/CreateTrainingPipelineVideoObjectTrackingSample.java
  samples/snippets/src/main/java/aiplatform/PredictImageObjectDetectionSample.java
  samples/snippets/src/main/java/aiplatform/PredictTabularClassificationSample.java
  samples/snippets/src/main/java/aiplatform/PredictTabularRegressionSample.java
  samples/snippets/src/main/java/aiplatform/PredictTextEntityExtractionSample.java
  samples/snippets/src/test/java/aiplatform/CreateBatchPredictionJobVideoClassificationSampleTest.java
  samples/snippets/src/test/java/aiplatform/CreateBatchPredictionJobVideoObjectTrackingSampleTest.java
  samples/snippets/src/test/java/aiplatform/CreateTrainingPipelineTabularClassificationSampleTest.java
  samples/snippets/src/test/java/aiplatform/CreateTrainingPipelineTabularRegressionSampleTest.java
  samples/snippets/src/test/java/aiplatform/CreateTrainingPipelineVideoActionRecognitionSampleTest.java
  samples/snippets/src/test/java/aiplatform/ExportModelSampleTest.java
  samples/snippets/src/test/java/aiplatform/ExportModelTabularClassificationSampleTest.java
  samples/snippets/src/test/java/aiplatform/GetModelEvaluationImageClassificationSampleTest.java
  samples/snippets/src/test/java/aiplatform/GetModelEvaluationImageObjectDetectionSampleTest.java
  samples/snippets/src/test/java/aiplatform/GetModelEvaluationSampleTest.java
  samples/snippets/src/test/java/aiplatform/GetModelEvaluationSliceSampleTest.java
  samples/snippets/src/test/java/aiplatform/GetModelEvaluationTabularClassificationSampleTest.java
  samples/snippets/src/test/java/aiplatform/GetModelEvaluationTabularRegressionSampleTest.java
  samples/snippets/src/test/java/aiplatform/GetModelEvaluationTextClassificationSampleTest.java
  samples/snippets/src/test/java/aiplatform/GetModelEvaluationTextEntityExtractionSampleTest.java
  samples/snippets/src/test/java/aiplatform/GetModelEvaluationTextSentimentAnalysisSampleTest.java
  samples/snippets/src/test/java/aiplatform/GetModelEvaluationVideoClassificationSampleTest.java
  samples/snippets/src/test/java/aiplatform/GetModelEvaluationVideoObjectTrackingSampleTest.java
  samples/snippets/src/test/java/aiplatform/GetModelSampleTest.java
  samples/snippets/src/test/java/aiplatform/ListModelEvaluationSliceSampleTest.java
Labels: cla: yes, samples

#142 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#143 build: migrate to flakybot
  .kokoro/build.sh
Labels: automerge, cla: yes
