Repository googleapis/java-aiplatform, pull requests merged in 2021-02, with the labels that each got.

#151 build(java): generate docfx yml on release
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#152 build(java): run linkage monitor as GitHub action
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#127 chore: update gapic-generator-java to 0.0.16
  google-cloud-aiplatform/src/test/java/com/google/cloud/aiplatform/v1beta1/JobServiceClientTest.java
  google-cloud-aiplatform/src/test/java/com/google/cloud/aiplatform/v1beta1/ModelServiceClientTest.java
  synth.metadata
Labels: cla: yes, context: full

#156 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/auto-release.yaml
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: automerge, cla: yes, context: full

#158 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#159 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#162 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#163 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#165 chore: generalize clirr ignored differences
  proto-google-cloud-aiplatform-v1beta1/clirr-ignored-differences.xml
Labels: api: aiplatform, cla: yes

#179 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: aiplatform, automerge, cla: yes

#183 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: aiplatform, automerge, cla: yes

#173 docs: updates prediction to new hostname
  samples/snippets/src/main/java/aiplatform/PredictCustomTrainedModelSample.java
  samples/snippets/src/main/java/aiplatform/PredictImageClassificationSample.java
  samples/snippets/src/main/java/aiplatform/PredictImageObjectDetectionSample.java
  samples/snippets/src/main/java/aiplatform/PredictTabularClassificationSample.java
  samples/snippets/src/main/java/aiplatform/PredictTabularRegressionSample.java
  samples/snippets/src/main/java/aiplatform/PredictTextClassificationSingleLabelSample.java
  samples/snippets/src/main/java/aiplatform/PredictTextEntityExtractionSample.java
  samples/snippets/src/main/java/aiplatform/PredictTextSentimentAnalysisSample.java
  samples/snippets/src/test/java/aiplatform/PredictImageObjectDetectionSampleTest.java
Labels: api: aiplatform, cla: yes
