Repository googleapis/java-aiplatform, pull requests merged in 2021-09, with the labels that each got.

#649 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: aiplatform

#651 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: aiplatform

#654 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: automerge, kokoro:force-run, cla: yes, api: aiplatform

#670 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: automerge, cla: yes, api: aiplatform

#686 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: aiplatform
