Repository googleapis/java-aiplatform, pull requests merged in 2021-05, with the labels that each got.

#238 samples: updates samples to v1 (7 of 8)
  samples/snippets/src/main/java/aiplatform/ImportDataImageClassificationSample.java
  samples/snippets/src/main/java/aiplatform/ImportDataImageObjectDetectionSample.java
  samples/snippets/src/main/java/aiplatform/ImportDataTextClassificationSingleLabelSample.java
  samples/snippets/src/main/java/aiplatform/ImportDataTextEntityExtractionSample.java
  samples/snippets/src/main/java/aiplatform/ImportDataTextSentimentAnalysisSample.java
  samples/snippets/src/main/java/aiplatform/ImportDataVideoActionRecognitionSample.java
  samples/snippets/src/main/java/aiplatform/ImportDataVideoClassificationSample.java
  samples/snippets/src/main/java/aiplatform/ImportDataVideoObjectTrackingSample.java
Labels: api: aiplatform, cla: yes, samples

#339 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: aiplatform, automerge, cla: yes

#236 samples: updates samples to v1 (6 of 8)
  samples/snippets/src/main/java/aiplatform/GetModelEvaluationImageClassificationSample.java
  samples/snippets/src/main/java/aiplatform/GetModelEvaluationImageObjectDetectionSample.java
  samples/snippets/src/main/java/aiplatform/GetModelEvaluationSample.java
  samples/snippets/src/main/java/aiplatform/GetModelEvaluationSliceSample.java
  samples/snippets/src/main/java/aiplatform/GetModelEvaluationTabularClassificationSample.java
  samples/snippets/src/main/java/aiplatform/GetModelEvaluationTabularRegressionSample.java
  samples/snippets/src/main/java/aiplatform/GetModelEvaluationTextClassificationSample.java
  samples/snippets/src/main/java/aiplatform/GetModelEvaluationTextEntityExtractionSample.java
  samples/snippets/src/main/java/aiplatform/GetModelEvaluationTextSentimentAnalysisSample.java
  samples/snippets/src/main/java/aiplatform/GetModelEvaluationVideoActionRecognitionSample.java
  samples/snippets/src/main/java/aiplatform/GetModelEvaluationVideoClassificationSample.java
  samples/snippets/src/main/java/aiplatform/GetModelEvaluationVideoObjectTrackingSample.java
Labels: api: aiplatform, cla: yes, samples

#239 samples: updates samples to v1 (8 of 8)
  samples/snippets/src/main/java/aiplatform/ListModelEvaluationSliceSample.java
  samples/snippets/src/main/java/aiplatform/PredictCustomTrainedModelSample.java
  samples/snippets/src/main/java/aiplatform/PredictImageClassificationSample.java
  samples/snippets/src/main/java/aiplatform/PredictImageObjectDetectionSample.java
  samples/snippets/src/main/java/aiplatform/PredictTabularClassificationSample.java
  samples/snippets/src/main/java/aiplatform/PredictTabularRegressionSample.java
  samples/snippets/src/main/java/aiplatform/PredictTextClassificationSingleLabelSample.java
  samples/snippets/src/main/java/aiplatform/PredictTextEntityExtractionSample.java
  samples/snippets/src/main/java/aiplatform/PredictTextSentimentAnalysisSample.java
  samples/snippets/src/main/java/aiplatform/UndeployModelSample.java
  samples/snippets/src/main/java/aiplatform/UploadModelSample.java
Labels: api: aiplatform, cla: yes, samples

#340 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: aiplatform, automerge, cla: yes, context: none

#343 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: aiplatform, automerge, cla: yes, context: full

#347 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: aiplatform, automerge, cla: yes

#350 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: aiplatform, automerge, cla: yes, context: full

#357 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: aiplatform, automerge, cla: yes, context: full

#356 feat: adds enhanced protos for time series forecasting
  google-cloud-aiplatform/src/main/java/com/google/cloud/aiplatform/v1beta1/FeaturestoreServiceClient.java
  google-cloud-aiplatform/src/test/java/com/google/cloud/aiplatform/v1beta1/FeaturestoreServiceClientTest.java
  proto-google-cloud-aiplatform-v1/clirr-ignored-differences.xml
  proto-google-cloud-aiplatform-v1beta1/clirr-ignored-differences.xml
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/AcceleratorType.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/AcceleratorTypeProto.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/Featurestore.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/FeaturestoreOrBuilder.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/FeaturestoreProto.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/FeaturestoreServiceProto.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/ImportFeatureValuesOperationMetadata.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/ImportFeatureValuesOperationMetadataOrBuilder.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/ImportFeatureValuesResponse.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/ImportFeatureValuesResponseOrBuilder.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/NearestNeighborSearchOperationMetadata.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/Tensorboard.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/UpdateFeaturestoreRequest.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/UpdateFeaturestoreRequestOrBuilder.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/schema/predict/prediction/TimeSeriesForecastingPredictionResult.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/schema/predict/prediction/TimeSeriesForecastingPredictionResultOrBuilder.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/schema/predict/prediction/TimeSeriesForecastingPredictionResultProto.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/schema/trainingjob/definition/AutoMLForecastingProto.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/schema/trainingjob/definition/AutoMlForecasting.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/schema/trainingjob/definition/AutoMlForecastingInputs.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/schema/trainingjob/definition/AutoMlForecastingInputsOrBuilder.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/schema/trainingjob/definition/AutoMlForecastingMetadata.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/schema/trainingjob/definition/AutoMlForecastingMetadataOrBuilder.java
  proto-google-cloud-aiplatform-v1beta1/src/main/java/com/google/cloud/aiplatform/v1beta1/schema/trainingjob/definition/AutoMlForecastingOrBuilder.java
  proto-google-cloud-aiplatform-v1beta1/src/main/proto/google/cloud/aiplatform/v1beta1/accelerator_type.proto
  proto-google-cloud-aiplatform-v1beta1/src/main/proto/google/cloud/aiplatform/v1beta1/featurestore.proto
  proto-google-cloud-aiplatform-v1beta1/src/main/proto/google/cloud/aiplatform/v1beta1/featurestore_service.proto
  proto-google-cloud-aiplatform-v1beta1/src/main/proto/google/cloud/aiplatform/v1beta1/index_service.proto
  proto-google-cloud-aiplatform-v1beta1/src/main/proto/google/cloud/aiplatform/v1beta1/schema/predict/prediction/time_series_forecasting.proto
  proto-google-cloud-aiplatform-v1beta1/src/main/proto/google/cloud/aiplatform/v1beta1/schema/trainingjob/definition/automl_time_series_forecasting.proto
  proto-google-cloud-aiplatform-v1beta1/src/main/proto/google/cloud/aiplatform/v1beta1/tensorboard.proto
  synth.metadata
Labels: api: aiplatform, automerge, cla: yes

#358 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: aiplatform, automerge, cla: yes

#362 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: aiplatform, automerge, cla: yes, context: full

#387 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: aiplatform, automerge, cla: yes
